#!/bin/bash

###
# Remove all images with <none> repository
###

IMAGE_HASH=$(docker images | grep "^<none>" | awk '{print $3}');
if [ ! -z "$IMAGE_HASH" ]
then
    docker rmi $IMAGE_HASH;
else
    echo "no unstagged image";
fi
