#!/bin/bash

###
# Remove all stopped containers
###

CONTAINER_HASH=$(docker ps --all --quiet --filter "status=exited")
if  [ ! -z "$CONTAINER_HASH" ]
then
    docker rm $CONTAINER_HASH;
else
    echo "no stopped container";
fi
